version: 2.1

orbs:
  pulumi: pulumi/pulumi@2.0.0
  gcp-gcr: circleci/gcp-gcr@0.13.0

jobs:
  build-and-publish-api:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: uniquey-api
          dockerfile: DockerfileApi
          tag: $CIRCLE_SHA1
          setup-remote-docker: true
          use-docker-layer-caching: true
      - gcp-gcr/push-image:
          image: uniquey-api
          tag: $CIRCLE_SHA1
          setup-remote-docker: true
          use-docker-layer-caching: true
  build-and-publish-web:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: uniquey-web
          dockerfile: DockerfileWeb
          tag: $CIRCLE_SHA1
      - gcp-gcr/push-image:
          image: uniquey-web
          tag: $CIRCLE_SHA1
  deploy:
    docker:
      - image: 'circleci/node:16'
    working_directory: ~/repo
    steps:
      - checkout
      - pulumi/login
      - run:
          command: cd pulumi && npm install
      - pulumi/update:
          working_directory: './pulumi/'
          stack: $CIRCLE_BRANCH

workflows:
  build-and-deploy:
    jobs:
      - gcp-gcr/build-and-push-image:
          context: uniquey-api
          executor: gcp-gcr/default
          image: uniquey-api
          tag: $CIRCLE_SHA1
          dockerfile: DockerfileApi
          setup-remote-docker: true
          use-docker-layer-caching: true
      - gcp-gcr/build-and-push-image:
          context: uniquey-web
          executor: gcp-gcr/default
          image: uniquey-web
          tag: $CIRCLE_SHA1
          dockerfile: DockerfileWeb
          setup-remote-docker: true
          use-docker-layer-caching: true
      - deploy:
          requires:
            - gcp-gcr/build-and-push-image