version: 2.1
orbs:
  pulumi: pulumi/pulumi@2.0.0
jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    working_directory: './pulumi/'
    steps:
      - checkout
      - pulumi/login
      - run:
          command: npm install
      - pulumi/update:
          stack: $CIRCLE_BRANCH