version: 2.1
orbs:
  pulumi: pulumi/pulumi@2.0.0
jobs:
  build:
    docker:
      - image: 'circleci/node:16'
    working_directory: ~/repo
    steps:
      - checkout
      - pulumi/login
      - run:
          command: cd pulumi && npm install
      - pulumi/update:
          working_directory: './pulumi/'
          stack: $CIRCLE_BRANCH