version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - uniquey_io_yarn-{{checksum "yarn.lock"}}
      - run:
          name: Set Yarn Cache
          command: yarn config set cache-folder .yarn_cache
      - run:
          name: Install Packages
          command: yarn --cache-folder .yarn_cache
      - run:
          name: Lerna Bootstrap
          command: yarn bootstrap
      - run:
          name: Build Workspaces
          command: yarn build
      - run:
          name: Export Static Web
          command: yarn export:web
      - save_cache:
          key: uniquey_io_yarn-{{checksum "yarn.lock"}}
          paths:
            - .yarn_cache
      - save_cache:
          key: uniquey_io_arch-{{ .Branch }}-{{ .Revision }}
          paths:
            - node_modules
            - packages/api/dist
            - packages/common/dist
            - packages/web/out
  lint: 
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - uniquey_io_arch-{{ .Branch }}-{{ .Revision }}
      - run: 
          name: Run Lint
          command: yarn lint
        
workflows:
  branch-job:
    jobs:
      - build
      - lint:
          requires:
            - build