version: 2.1

orbs:
  pulumi: pulumi/pulumi@2.0.0
  gcp-gcr: circleci/gcp-gcr@0.13.0

jobs:
   deploy:
    docker:
      - image: 'circleci/node:16'
    working_directory: ~/repo
    steps:
      - checkout
      - pulumi/login
      - run:
          command: cd pulumi && npm install
      - pulumi/update:
          working_directory: './pulumi/'
          stack: $CIRCLE_BRANCH

workflows:
  build-and-deploy:
    jobs:
      - gcp-gcr/build-and-push-image:
          name: build-api
          image: uniquey-api
          tag: $CIRCLE_SHA1
          dockerfile: DockerfileApi
          executer: docker:latest
          setup-remote-docker: true
          use-docker-layer-caching: true
      - gcp-gcr/build-and-push-image:
          name: build-web
          image: uniquey-web
          tag: $CIRCLE_SHA1
          dockerfile: DockerfileWeb
          executer: docker:latest
          setup-remote-docker: true
          use-docker-layer-caching: true
      - deploy:
          requires:
            - build-web
            - build-api